// Document text extraction for TXT, MD, and PDF files.
// PDF parsing uses a regex-based heuristic on the raw buffer — it recovers text from simple
// PDFs without pdfjs-dist. Complex PDFs with embedded fonts will return partial text;
// full fidelity requires a future pdfjs-dist or hosted converter upgrade.
// DOCX/PPTX require mammoth/libreoffice which are not yet in the dependency set (Phase 2b deferred).

export type ExtractedDocument = {
  text: string
  headings: string[]
  pageCount?: number
  truncated: boolean
}

const MAX_CHARS = 8000

// ─── PDF text heuristic ───────────────────────────────────────────────────────
// Extracts text tokens from a PDF buffer using regex. Works well for text-heavy PDFs
// generated by standard toolchains; fails silently on scanned or heavily-fonted PDFs.

function extractPdfText(buf: Buffer): { text: string; pageCount: number } {
  const raw = buf.toString("binary")

  // Count pages via /Type /Page dictionaries
  const pageMatches = raw.match(/\/Type\s*\/Page[^s]/g)
  const pageCount = pageMatches ? pageMatches.length : 1

  // Extract text from BT...ET blocks and parenthesized strings
  const tokens: string[] = []

  // BT ... ET blocks contain text operators like (string) Tj or [(str)-...] TJ
  const btBlocks = raw.matchAll(/BT([\s\S]*?)ET/g)
  for (const [, block] of btBlocks) {
    // Parenthesized strings: (Hello world)
    for (const [, s] of block.matchAll(/\(([^)\\]{1,200})\)/g)) {
      const decoded = s
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\n")
        .replace(/\\t/g, " ")
        .replace(/\\\(/g, "(")
        .replace(/\\\)/g, ")")
        .replace(/\\\\/g, "\\")
      tokens.push(decoded)
    }
    // Hex strings: <48656c6c6f>
    for (const [, hex] of block.matchAll(/<([0-9a-f]{2,})>/gi)) {
      const decoded = hex
        .match(/.{2}/g)
        ?.map((h) => String.fromCharCode(parseInt(h, 16)))
        .filter((c) => c.charCodeAt(0) >= 32)
        .join("") ?? ""
      if (decoded.trim()) tokens.push(decoded)
    }
  }

  // Collapse whitespace and join
  const text = tokens
    .join(" ")
    .replace(/\s+/g, " ")
    .replace(/[^\x20-\x7E\n]/g, "")  // keep only printable ASCII
    .trim()

  return { text, pageCount }
}

// ─── Markdown/text heading extraction ─────────────────────────────────────────

function extractHeadings(text: string): string[] {
  return text
    .split("\n")
    .filter((line) => /^#{1,3}\s+/.test(line))
    .map((line) => line.replace(/^#{1,3}\s+/, "").trim())
    .filter(Boolean)
    .slice(0, 30)
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function extractFromDocument(
  buf: Buffer,
  mimeType: string,
  filename: string,
): ExtractedDocument {
  const ext = (filename.split(".").pop() ?? "").toLowerCase()

  // Plain text or markdown
  if (
    mimeType.startsWith("text/") ||
    ext === "txt" ||
    ext === "md" ||
    ext === "markdown"
  ) {
    const raw = buf.toString("utf8")
    const text = raw.slice(0, MAX_CHARS)
    return {
      text,
      headings: extractHeadings(raw),
      truncated: raw.length > MAX_CHARS,
    }
  }

  // PDF
  if (mimeType === "application/pdf" || ext === "pdf") {
    const { text, pageCount } = extractPdfText(buf)
    return {
      text: text.slice(0, MAX_CHARS),
      headings: [],
      pageCount,
      truncated: text.length > MAX_CHARS,
    }
  }

  // DOCX / DOC — requires mammoth (not yet installed). Return empty with note.
  if (
    mimeType.includes("wordprocessingml") ||
    mimeType === "application/msword" ||
    ext === "docx" ||
    ext === "doc"
  ) {
    return { text: "", headings: [], truncated: false }
  }

  return { text: "", headings: [], truncated: false }
}

export function dataUrlToBuffer(dataUrl: string): Buffer | null {
  try {
    const comma = dataUrl.indexOf(",")
    if (comma === -1) return null
    const b64 = dataUrl.slice(comma + 1)
    return Buffer.from(b64, "base64")
  } catch {
    return null
  }
}
